# Generated by Django 4.2.16 on 2026-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='expected_players',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='teams_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
