# Generated by Django 4.2.16 on 2026-05-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('peek_accepted', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectators', to='game.game')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectators', to='game.player')),
            ],
            options={
                'unique_together': {('game', 'username')},
            },
        ),
    ]
