# Generated by Django 4.2.16 on 2026-05-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_spectator'),
    ]

    operations = [
        migrations.AddField(
            model_name='trickcard',
            name='hand_before',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='BidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('seat', models.PositiveSmallIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('trump_suit', models.CharField(max_length=10)),
                ('trump_card', models.JSONField(blank=True, default=dict, null=True)),
                ('hand_snapshot', models.JSONField(default=list)),
                ('others_bids_before', models.JSONField(default=list)),
                ('bid_made', models.SmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_logs', to='game.game')),
            ],
            options={
                'ordering': ['round_number', 'seat'],
            },
        ),
    ]
