# Generated by Django 4.2.16 on 2026-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_trickcard_hand_before_bidlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlog',
            name='all_scores_before_round',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trickcard',
            name='all_bids_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trickcard',
            name='all_scores_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trickcard',
            name='all_tricks_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
