# Generated by Django 4.2.16 on 2026-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_resume_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='declared',
            field=models.BooleanField(default=False),
        ),
    ]
